/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: {
          canvas: 'var(--surface-canvas)',
          primary: 'var(--surface-primary)',
          secondary: 'var(--surface-secondary)',
          raised: 'var(--surface-raised)',
          elevated: 'var(--surface-elevated)',
          muted: 'var(--surface-muted)',
          overlay: 'var(--surface-overlay)',
          glass: 'var(--surface-glass)',
          hover: 'var(--surface-hover)',
        },
        background: {
          primary: 'var(--bg-primary)',
          surface: 'var(--bg-surface)',
          'surface-alt': 'var(--bg-surface-alt)',
        },
        border: {
          DEFAULT: 'var(--border-primary)',
          subtle: 'var(--border-subtle)',
          muted: 'var(--border-muted)',
          strong: 'var(--border-strong)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
          subtle: 'var(--text-subtle)',
          disabled: 'var(--text-disabled)',
          inverse: 'var(--text-inverse)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          hover: 'var(--accent-hover)',
          info: 'var(--accent-info)',
          secondary: 'var(--accent-secondary)',
          cyan: 'var(--accent-info)',
          purple: 'var(--accent)',
          green: 'var(--status-success)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          hover: 'var(--primary-hover)',
        },
        success: 'var(--status-success)',
        warning: 'var(--status-warning)',
        danger: 'var(--status-danger)',
        panel: {
          bg: 'var(--panel-bg)',
          border: 'var(--panel-border)',
        },
      },
      fontFamily: {
        sans: ['Outfit', 'Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      backgroundImage: {
        'gradient-primary': 'var(--gradient-primary)',
        'gradient-accent': 'var(--gradient-accent)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        full: 'var(--radius-pill)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        popover: 'var(--shadow-popover)',
        focus: 'var(--focus-ring)',
        'info-glow': 'var(--info-glow)',
        'info-glow-subtle': 'var(--info-glow-subtle)',
        'info-glow-strong': 'var(--info-glow-strong)',
        'success-glow': 'var(--glow-success)',
        'danger-glow': 'var(--glow-danger)',
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
      },
    },
  },
  plugins: [],
}
