[workspace]
members = [
    "contracts/agent_registry",
    "contracts/error-resolver",
    "contracts/error-registry",
    "contracts/agent_bidding",
    "contracts/upgrade-manager",
    "contracts/price_oracle",
    "contracts/oracle_manager",
    "contracts/agent_marketplace",
    "contracts/task_store",
]
resolver = "2"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
