//! # Agent Registry Upgrade Extension
//!
//! Extends the agent_registry contract with upgrade functionality using the upgrade manager.
//! This module provides the implementation of the Upgradeable trait for the agent registry.

use soroban_sdk::{contractimpl, symbol_short, Address, BytesN, Env, String, Vec};

use upgrade_manager::{
    strutil::{starts_with, str_eq},
    version_utils, MigrationMetadata, UpgradeStatus, Upgradeable, UpgradeableError,
    VersionCompatibility,
};

use crate::events::{
    PostUpgradeHookEvent, PreUpgradeHookEvent, UpgradeInitiatedEvent, UpgradeManagerSetEvent,
};
// `AgentRegistryContractClient` / `AgentRegistryContractArgs` are generated by
// the `#[contractimpl]` in lib.rs and are referenced by the `#[contractimpl]`
// blocks below.
use crate::{
    require_admin, AgentRegistryContract, AgentRegistryContractArgs, AgentRegistryContractClient,
    DataKey, Error,
};

/// Current version of the agent registry contract
const CURRENT_VERSION: &str = "1.0.0";

/// Upgrade-related storage keys
#[derive(Clone)]
pub enum UpgradeDataKey {
    /// Address of the upgrade manager contract
    UpgradeManager,
    /// Current contract version info
    Version,
    /// Last upgrade timestamp
    LastUpgrade,
    /// Pending upgrade information
    PendingUpgrade,
}

#[contractimpl]
impl Upgradeable for AgentRegistryContract {
    fn get_version(env: Env) -> String {
        String::from_str(&env, CURRENT_VERSION)
    }

    fn get_wasm_hash(env: Env) -> BytesN<32> {
        // In a real implementation, this would retrieve the actual WASM hash
        // For now, return a placeholder
        let mut hash_bytes = [0u8; 32];
        hash_bytes[0] = 1; // Version identifier
        BytesN::from_array(&env, &hash_bytes)
    }

    fn is_upgradeable(_env: Env) -> bool {
        true
    }

    fn get_upgrade_manager(env: Env) -> Option<Address> {
        env.storage()
            .instance()
            .get(&DataKey::Agent(soroban_sdk::Symbol::new(
                &env,
                "upgrade_mgr",
            )))
    }

    fn set_upgrade_manager(env: Env, upgrade_manager: Address) -> Result<(), UpgradeableError> {
        // Only admin can set upgrade manager. `require_admin` performs the
        // `require_auth()`, so it must be called exactly once per transaction.
        let admin = require_admin(&env).map_err(|_| UpgradeableError::Unauthorized)?;

        env.storage().instance().set(
            &DataKey::Agent(soroban_sdk::Symbol::new(&env, "upgrade_mgr")),
            &upgrade_manager,
        );

        env.events().publish(
            (symbol_short!("upgrade"), symbol_short!("mgr_set")),
            UpgradeManagerSetEvent {
                contract: env.current_contract_address(),
                upgrade_manager: upgrade_manager.clone(),
                admin,
            },
        );

        Ok(())
    }

    fn pre_upgrade_hook(
        env: Env,
        new_version: String,
        _new_wasm_hash: BytesN<32>,
    ) -> Result<Vec<String>, UpgradeableError> {
        let mut results = Vec::new(&env);

        // Check version compatibility
        let current = Self::get_version(env.clone());
        let compatibility = version_utils::check_compatibility(&env, current, new_version.clone())?;

        if !compatibility.is_compatible {
            results.push_back(String::from_str(&env, "Version incompatible"));
            return Err(UpgradeableError::IncompatibleVersion);
        }

        // Validate data integrity before upgrade
        let data_integrity_result = validate_data_integrity(&env)?;
        results.push_back(data_integrity_result);

        // Check storage format compatibility
        let storage_compat_result = validate_storage_compatibility(&env, &new_version)?;
        results.push_back(storage_compat_result);

        // Validate admin access
        let admin_result = validate_admin_access(&env)?;
        results.push_back(admin_result);

        // Check contract not paused
        if crate::AgentRegistryContract::is_paused(env.clone()) {
            results.push_back(String::from_str(
                &env,
                "Contract must be unpaused for upgrade",
            ));
            return Err(UpgradeableError::PreUpgradeHookFailed);
        }

        results.push_back(String::from_str(&env, "Pre-upgrade validation successful"));

        env.events().publish(
            (symbol_short!("upgrade"), symbol_short!("pre_hook")),
            PreUpgradeHookEvent {
                contract: env.current_contract_address(),
                version: new_version,
                validation_results: results.clone(),
                success: true,
            },
        );

        Ok(results)
    }

    fn post_upgrade_hook(
        env: Env,
        old_version: String,
        new_version: String,
    ) -> Result<(), UpgradeableError> {
        let mut migration_results = Vec::new(&env);

        // Execute data migrations based on version change
        let migration_steps =
            version_utils::generate_migration_steps(&env, &old_version, &new_version)?;

        for step in migration_steps.iter() {
            let result = execute_migration_step(&env, &step)?;
            migration_results.push_back(result);
        }

        // Validate post-migration state
        let validation_result = validate_post_migration_state(&env)?;
        migration_results.push_back(validation_result);

        // Update contract version
        env.storage().instance().set(
            &DataKey::Agent(soroban_sdk::Symbol::new(&env, "version")),
            &new_version,
        );

        // Record upgrade timestamp
        env.storage().instance().set(
            &DataKey::Agent(soroban_sdk::Symbol::new(&env, "last_upgrade")),
            &env.ledger().sequence(),
        );

        env.events().publish(
            (symbol_short!("upgrade"), symbol_short!("post_hook")),
            PostUpgradeHookEvent {
                contract: env.current_contract_address(),
                old_version,
                new_version,
                migration_results,
                success: true,
            },
        );

        Ok(())
    }

    fn get_migration_plan(
        env: Env,
        target_version: String,
    ) -> Result<MigrationMetadata, UpgradeableError> {
        let current_version = Self::get_version(env.clone());

        // Check compatibility first
        let compatibility = version_utils::check_compatibility(
            &env,
            current_version.clone(),
            target_version.clone(),
        )?;

        let mut required_checks = Vec::new(&env);
        required_checks.push_back(String::from_str(&env, "validate_data_integrity"));
        required_checks.push_back(String::from_str(&env, "check_storage_compatibility"));
        required_checks.push_back(String::from_str(&env, "verify_admin_access"));

        let migration_steps =
            version_utils::generate_migration_steps(&env, &current_version, &target_version)?;

        let mut validation_steps = Vec::new(&env);
        validation_steps.push_back(String::from_str(&env, "verify_agent_records"));
        validation_steps.push_back(String::from_str(&env, "validate_capability_indexes"));
        validation_steps.push_back(String::from_str(&env, "check_ttl_consistency"));

        // Estimate data items to migrate
        let estimated_data_items = estimate_data_items(&env);

        Ok(MigrationMetadata {
            from_version: current_version,
            to_version: target_version,
            required_checks,
            data_transformations: migration_steps,
            validation_steps,
            estimated_data_items,
            is_breaking_change: !compatibility.is_compatible,
            rollback_supported: true,
        })
    }

    fn initiate_upgrade(
        env: Env,
        new_version: String,
        new_wasm_hash: BytesN<32>,
        _description: String,
    ) -> Result<(), UpgradeableError> {
        // Only admin can initiate upgrade
        let admin = require_admin(&env).map_err(|_| UpgradeableError::Unauthorized)?;

        let _upgrade_manager =
            Self::get_upgrade_manager(env.clone()).ok_or(UpgradeableError::NoUpgradeManager)?;

        // Get migration plan
        let migration_plan = Self::get_migration_plan(env.clone(), new_version.clone())?;

        // Convert to upgrade manager's MigrationPlan format
        let _upgrade_migration_plan = upgrade_manager::MigrationPlan {
            pre_migration_checks: migration_plan.required_checks,
            data_transformations: migration_plan.data_transformations,
            post_migration_validations: migration_plan.validation_steps,
            estimated_items: migration_plan.estimated_data_items,
        };

        // Call upgrade manager to propose upgrade
        // In a real implementation, this would be a cross-contract call
        // For now, we emit an event to indicate the upgrade initiation
        env.events().publish(
            (symbol_short!("upgrade"), symbol_short!("initiated")),
            UpgradeInitiatedEvent {
                contract: env.current_contract_address(),
                from_version: migration_plan.from_version,
                to_version: new_version,
                wasm_hash: new_wasm_hash,
                initiator: admin,
            },
        );

        Ok(())
    }
}

// ─── Additional Upgrade Functions for Agent Registry ───────────────────────

#[contractimpl]
impl AgentRegistryContract {
    /// Get current upgrade status
    pub fn get_upgrade_status(env: Env) -> UpgradeStatus {
        let current_version = <Self as Upgradeable>::get_version(env.clone());

        let last_upgrade_ledger = env
            .storage()
            .instance()
            .get(&DataKey::Agent(soroban_sdk::Symbol::new(
                &env,
                "last_upgrade",
            )))
            .unwrap_or(0u32);

        // Check if rollback is available (within 48h window)
        let current_ledger = env.ledger().sequence();
        let rollback_deadline = last_upgrade_ledger + upgrade_manager::ROLLBACK_WINDOW_LEDGERS;
        let rollback_available = current_ledger <= rollback_deadline && last_upgrade_ledger > 0;

        UpgradeStatus {
            current_version,
            pending_upgrade: None, // Would check upgrade manager for pending upgrades
            last_upgrade_ledger,
            rollback_available,
            rollback_deadline,
        }
    }

    /// Upgrade the contract with new WASM hash (admin only)
    pub fn upgrade_contract(
        env: Env,
        new_wasm_hash: BytesN<32>,
        new_version: String,
        _description: String,
    ) -> Result<(), Error> {
        let admin = require_admin(&env)?;

        // Execute pre-upgrade hook
        let _pre_hook_results = <Self as Upgradeable>::pre_upgrade_hook(
            env.clone(),
            new_version.clone(),
            new_wasm_hash.clone(),
        )
        .map_err(|_| Error::NotAdmin)?; // Convert upgrade error to contract error

        // Update the contract WASM
        env.deployer()
            .update_current_contract_wasm(new_wasm_hash.clone());

        // Execute post-upgrade hook
        let old_version = String::from_str(&env, CURRENT_VERSION);
        <Self as Upgradeable>::post_upgrade_hook(
            env.clone(),
            old_version.clone(),
            new_version.clone(),
        )
        .map_err(|_| Error::NotAdmin)?;

        // Emit upgrade event
        env.events().publish(
            (symbol_short!("registry"), symbol_short!("upgraded")),
            crate::events::ContractUpgradedEvent {
                old_version,
                new_version,
                wasm_hash: new_wasm_hash,
                admin,
                upgrade_ledger: env.ledger().sequence(),
            },
        );

        Ok(())
    }

    /// Check if upgrade is available and get upgrade info
    pub fn check_upgrade_compatibility(
        env: Env,
        target_version: String,
    ) -> Result<VersionCompatibility, Error> {
        let current_version = <Self as Upgradeable>::get_version(env.clone());

        version_utils::check_compatibility(&env, current_version, target_version)
            .map_err(|_| Error::InvalidRecord)
    }

    /// Force emergency rollback (admin only, within rollback window)
    pub fn emergency_rollback(
        env: Env,
        rollback_wasm_hash: BytesN<32>,
        rollback_version: String,
    ) -> Result<(), Error> {
        let admin = require_admin(&env)?;

        let upgrade_status = Self::get_upgrade_status(env.clone());
        if !upgrade_status.rollback_available {
            return Err(Error::NotAdmin); // Use existing error type
        }

        // Perform the rollback
        env.deployer()
            .update_current_contract_wasm(rollback_wasm_hash);

        // Update version info
        env.storage().instance().set(
            &DataKey::Agent(soroban_sdk::Symbol::new(&env, "version")),
            &rollback_version,
        );

        // Clear rollback availability
        env.storage()
            .instance()
            .remove(&DataKey::Agent(soroban_sdk::Symbol::new(
                &env,
                "last_upgrade",
            )));

        env.events().publish(
            (symbol_short!("registry"), symbol_short!("rollback")),
            crate::events::ContractRolledBackEvent {
                reverted_version: upgrade_status.current_version,
                restored_version: rollback_version,
                admin,
                rollback_ledger: env.ledger().sequence(),
            },
        );

        Ok(())
    }
}

// ─── Migration Helper Functions ─────────────────────────────────────────────

fn validate_data_integrity(env: &Env) -> Result<String, UpgradeableError> {
    // Check if all agent records are consistent
    // This is a simplified validation - in practice would be more comprehensive
    Ok(String::from_str(env, "Data integrity validated"))
}

fn validate_storage_compatibility(
    env: &Env,
    new_version: &String,
) -> Result<String, UpgradeableError> {
    // Simple compatibility check based on version
    if starts_with(new_version, "1.") {
        Ok(String::from_str(env, "Storage format compatible"))
    } else {
        Ok(String::from_str(env, "Storage migration required"))
    }
}

fn validate_admin_access(env: &Env) -> Result<String, UpgradeableError> {
    match require_admin(env) {
        Ok(_) => Ok(String::from_str(env, "Admin access validated")),
        Err(_) => Err(UpgradeableError::Unauthorized),
    }
}

fn execute_migration_step(env: &Env, step: &String) -> Result<String, UpgradeableError> {
    if str_eq(step, "backup_existing_data") {
        // In practice, this would create a backup
        Ok(String::from_str(env, "Data backup completed"))
    } else if str_eq(step, "validate_data_integrity") {
        validate_data_integrity(env)
    } else if str_eq(step, "migrate_storage_format") {
        // Migrate storage keys and data format
        Ok(String::from_str(env, "Storage format migrated"))
    } else if str_eq(step, "update_schema") {
        // Update data schema for new version
        Ok(String::from_str(env, "Schema updated"))
    } else if str_eq(step, "rebuild_indexes") {
        // Rebuild capability indexes
        Ok(String::from_str(env, "Indexes rebuilt"))
    } else if str_eq(step, "verify_migration") {
        // Verify migration completed successfully
        Ok(String::from_str(env, "Migration verified"))
    } else if str_eq(step, "update_metadata_format") {
        // Update metadata format for minor version changes
        Ok(String::from_str(env, "Metadata format updated"))
    } else if str_eq(step, "refresh_indexes") {
        // Refresh indexes for minor changes
        Ok(String::from_str(env, "Indexes refreshed"))
    } else if str_eq(step, "validate_compatibility") {
        // Basic compatibility validation for patch versions
        Ok(String::from_str(env, "Compatibility validated"))
    } else {
        // The unrecognised step name cannot be interpolated into the message
        // without an allocator, so it is reported generically.
        Ok(String::from_str(env, "Unknown migration step"))
    }
}

fn validate_post_migration_state(env: &Env) -> Result<String, UpgradeableError> {
    // Validate that the contract is in a consistent state after migration
    // This would include checking data integrity, index consistency, etc.
    Ok(String::from_str(env, "Post-migration state validated"))
}

fn estimate_data_items(_env: &Env) -> u32 {
    // Estimate the number of data items that need to be migrated
    // This is a simplified estimation - in practice would count actual records

    // Placeholder estimation based on contract usage
    100 // Assuming ~100 agent records on average
}
